### ISSUE TITLE
"-*" checker not found in available checkers

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#1060]
I've noticed this error in Sentry.

From https://hg.mozilla.org/mozilla-central/raw-file/tip/tools/clang-tidy/config.yaml:
```
clang_checkers:
 - name: -*
   publish: !!bool no
 - name: misc-forward-declaration-namespace
   # Name with clang tidy 6.0. We are currently using 5.0
   # - name: bugprone-forward-declaration-namespace
   publish: !!bool yes
 ...
```
